import { makeStyles } from "@mui/styles";

const drawerWidth = 250;

export const useStyles = makeStyles((theme) => ({
  sideBarRoot: {
    color: "rgb(33, 43, 54)",
    transition: "width 0.3s ease-in-out",
    backgroundImage: "none",
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    height: "80vh",
    flex: "1 0 auto",
    position: "fixed", // Make it overlap
    top: "80px",
    left: "20px",
    zIndex: 1300, // High enough to be above other content
    outline: "0px",
    backgroundColor: "#fff",
    borderRadius: "20px", // Apply curve only on right side
    cursor: "pointer",
    width: "220px",
    boxShadow: "0px 8.23px 28.8px 0px #4859661A",
    "&.collapsed": {
      width: "55px",
    },
  },

  profile: {
    height: "40px",
    width: "40px",
    borderRadius: "100%",
    userSelect: "none",
    objectFit: "cover",
    textAlign: "center",
    border: "1px solid #1EA5FC",
  },
  profileText: {
    margin: "0px",
    fontWeight: "400",
    lineHeight: "1.57143",
    fontSize: "0.875rem",
    fontFamily: '"Public Sans", sans-serif',
    color: "rgb(33, 43, 54)",
  },
  profileView: {
    display: "flex",
    flexDirection: "row",
    WebkitBoxAlign: "center",
    alignItems: "center",
    padding: "16px 20px",
    borderRadius: "9px",
    backgroundColor: "rgba(145, 158, 171, 0.12)",
    gap: "1rem",
  },
  profilewrap: {
    margin: "20px",
    marginBottom: 0,
  },
  menuwrap: {
    margin: "1rem 8px",
    gap: ".4rem",
  },
  menuRoot: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "1rem",
    WebkitTapHighlightColor: "transparent",
    backgroundColor: "transparent",
    outline: "0px",
    border: "0px",
    padding: "8px 12px",
    cursor: "pointer",
    userSelect: "none",
    verticalAlign: "middle",
    appearance: "none",
    display: "flex",
    flexDirection: "row",
    WebkitBoxFlex: "1",
    justifyContent: "flex-start",
    alignItems: "center",
    textDecoration: "none",
    boxSizing: "border-box",
    textAlign: "left",
    transition: "background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms",
    lineHeight: "1.57143",
    fontSize: "0.875rem",
    fontFamily: '"Public Sans", sans-serif',
    fontWeight: "400",
    height: "36px",
    position: "relative",
    textTransform: "capitalize",
    color: "rgb(99, 115, 129)",
    borderRadius: "4px",
    color: "rgb(33, 43, 54)",
    fontWeight: "700",
    position: "relative",
  },
  menuLeft: {
    position: "absolute",
    left: 0,
    width: "2.88px",
    height: "24px",
    backgroundColor: theme.palette.primary.main,
    borderRadius: "3px",
  },
  menuicon: {
    flexShrink: "0",
    width: "22px",
    height: "22px",
    color: "inherit",
    display: "flex",
    WebkitBoxAlign: "center",
    alignItems: "center",
    WebkitBoxPack: "center",
    justifyContent: "center",
  },
  logout: {
    display: "flex",
    flexDirection: "column",
    rowGap: "24px",
    marginLeft: "16px",
    marginTop: "60px",
    paddingBottom: "30px",
    width: "100%",
  },
}));
