import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles((theme) => ({
  root: {
    width: "100%",
    height: "100%",
  },
  spaceBetween: {
    // margin: `0 ${theme.spacing(2)}`,
  },
  label: {
    fontWeight: 600,
    // fontSize: theme.fonts.heading,
  },
  distinct: {
    // marginTop: theme.spacingArea.doubleLarge,
  },
  gapMedium: {
    // gap: theme.spacingArea.XLarge,
  },
  input: {
    borderRadius: "8px",
    border: "1px solid #E5E5E5",
    overflow: "hidden",
    fontSize: "14px",
    // marginTop: theme.spacingArea.xSmall,
  },

  panelHeader: {
    backgroundColor: theme.palette.primary.light,
  },
  dropdown: {
    border: "1.5px solid #E5E5E5",
    borderRadius: "8px",
    width: "100%",
    height: "49px",
    display: "flex",
    alignItems: "center",
  },
  tablistStyles: {
    fontSize: "18px",
  },
  subscriptionHeader: {
    // backgroundColor: theme?.palette?.background?.default,
    borderTopLeftRadius: "15px",
    borderTopRightRadius: "15px",
    height: "50px",
    paddingBottom: "12px",
  },
  renewButton: {
    // backgroundColor: theme?.palette?.primary?.main,
    color: "#fff",
    "&:hover": {
      // backgroundColor: theme?.palette?.primary?.main,
      color: "#fff",
    },
    padding: "8px 30px",
    borderRadius: "8px",
    textTransform: "capitalize",
  },
  UserSubscriptionContainer: {
    marginTop: "20px",
    boxShadow: "0px 7px 17px 0px #0000001A",
    borderBottomLeftRadius: "15px",
    borderBottomRightRadius: "15px",
  },
  renewContainer: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "20px",
    // padding: "16px",
  },
  renewTextContainer: {
    display: "flex",
    flexDirection: "column",
  },
  currentPlanSection: {},
  noRatingsContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginTop: "50px",
  },
  projectBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px",
    borderRadius: "11px",
    backgroundColor: theme.palette.primary.light,
  },
  container: {
    position: "relative",
    width: "160px",
    height: "139px",
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
    margin: "auto",
    background: "#fff",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "opacity 0.5s ease-in-out",
    position: "absolute",
    top: 0,
    left: 0,
  },
  dotsContainer: {
    position: "absolute",
    bottom: "10px",
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    gap: "8px",
  },
  dot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    background: "#ccc",
    cursor: "pointer",
  },
  activeDot: {
    background: "#E53935",
  },

  //progress

  scrollContainer: {
    position: "relative",
    overflowX: "auto",
    padding: "20px 0",
    scrollbarWidth: "none",
  },
  scrollInner: {
    display: "flex",
    gap: "40px",
    position: "relative",
    minWidth: "max-content",
  },
  timelineLine: (props) => ({
    position: "absolute",
    top: "50%",
    height: "2px",
    backgroundColor: "#ccc",
    zIndex: 0,
    border: "4px solid",
    borderImageSource:
      "linear-gradient(90deg, #C4E8C4 0%, #E8C6C4 22%, #E8E4C4 46.5%, #C4E8E3 74%, #C4C8E8 100%)",
    borderImageSlice: 1,
  }),
  dotWrapper: {
    position: "relative",
    minWidth: "15px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  initialDot: {
    position: "absolute",
    top: "51%",
    width: "13px",
    height: "13px",
    backgroundColor: "#41080c",
    borderRadius: "50%",
    transform: "translateY(-50%)",
    zIndex: 1,
  },
  createdText: {
    marginTop: "61px",
    marginRight: "-50px",
    textAlign: "center",
    fontSize: "12px",
    color: "#666",
  },
  itemWrapper: {
    position: "relative",
    minWidth: "180px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 1,
  },
  contentTop: {
    marginBottom: "220px",
    borderRadius: "6px",
    width: "160px",
    padding: "10px",
  },
  contentBottom: {
    marginTop: "300px",
    borderRadius: "6px",
    width: "160px",
    padding: "10px",
    textAlign: "left",
  },
  timelineDot: {
    position: "absolute",
    top: "51%",
    width: "13px",
    height: "13px",
    backgroundColor: "#561E1E",
    borderRadius: "50%",
    transform: "translateY(-50%)",
    zIndex: 1,
  },
  loadMoreWrapper: {
    position: "relative",
    minWidth: "50px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    zIndex: 1,
  },
  moreCount: {
    backgroundColor: "#fde8e8",
    color: "#000",
    fontSize: "14px",
    padding: "4px 10px",
    borderRadius: "10px",
    marginBottom: "10px",
    marginTop: "120px",
  },
  loadMoreBtn: {
    position: "absolute",
    top: "50%",
    width: "25px",
    height: "25px",
    backgroundColor: "#41080c",
    borderRadius: "50%",
    transform: "translateY(-50%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
}));
