import {
  Board24Filled,
  Board24Regular,
  Megaphone24Filled,
  Megaphone24Regular,
  PeopleCall24Filled,
  PeopleCall24Regular,
  PeopleCheckmark24Filled,
  PeopleCheckmark24Regular,
  PeopleTeam24Filled,
  PeopleTeam24Regular,
  ClipboardTaskAdd24Filled,
  ClipboardTaskAdd24Regular,
  Calendar24Regular,
  Calendar24Filled,
  CollectionsAdd24Regular,
  CollectionsAdd24Filled,
  ClockBill24Filled,
  ClockBill24Regular,
  DocumentBulletList24Regular,
  DocumentBulletList24Filled,
  ClipboardClock24Filled,
  ClipboardClock24Regular,
} from "@fluentui/react-icons";

class SideBarMenu {
  static menuForSuperAdmin = [
    {
      display: "sideNavMenu.dashboard",
      link: "/admin/dashboard",
      linkPage: false,
      onclick: null,
      urlEndWith: "dashboard",
      className: "",
      permissionLevel: "Dashboard",
      regularIcon: <Board24Regular />,
      filledIcon: <Board24Filled style={{ color: "#C98383" }} />,
      eventKey: "dashboard",
      subMenu: [],
    },

    {
      display: "sideNavMenu.users",
      link: "/admin/users",
      linkPage: false,
      onclick: null,
      urlEndWith: "users",
      className: "",
      permissionLevel: "Users",
      regularIcon: <PeopleTeam24Regular />,
      filledIcon: <PeopleTeam24Filled style={{ color: "#C98383" }} />,
      eventKey: "users",
      subMenu: [],
    },
    {
      display: "sideNavMenu.projects",
      link: "/admin/projects",
      linkPage: false,
      onclick: null,
      urlEndWith: "projects",
      className: "",
      permissionLevel: "Projects",
      regularIcon: <DocumentBulletList24Regular />,
      filledIcon: <DocumentBulletList24Filled style={{ color: "#C98383" }} />,
      eventKey: "projects",
      subMenu: [],
    },
    {
      display: "sideNavMenu.campaigns",
      link: "/admin/campaigns",
      linkPage: false,
      onclick: null,
      urlEndWith: "campaigns",
      className: "",
      permissionLevel: "Campaigns",
      regularIcon: <DocumentBulletList24Regular />,
      filledIcon: <DocumentBulletList24Filled style={{ color: "#C98383" }} />,
      eventKey: "campaigns",
      subMenu: [],
    },
    {
      display: "sideNavMenu.security",
      link: "/admin/security/role",
      linkPage: false,
      onclick: null,
      urlEndWith: "security",
      className: "",
      permissionLevel: "Security",
      regularIcon: <PeopleCall24Regular />,
      filledIcon: <PeopleCall24Filled />,
      eventKey: "security",
      isExpandIconVisible: true,
      stylesForExpandedMenu: (pathUrl, displayName) =>
        // pass the url which is common in all the sub menus like /admin/security which is common in  roles
        pathUrl.includes("/admin/security") &&
        displayName === "sideNavMenu.security",
      subMenu: [
        {
          display: "sideNavMenu.role_function",
          link: "/admin/security/role",
          linkPage: false,
          onclick: null,
          urlEndWith: "role",
          className: "",
          permissionLevel: "Role",
          regularIcon: <PeopleCheckmark24Regular />,
          filledIcon: <PeopleCheckmark24Filled />,
          eventKey: "role",
        },
      ],
    },
    {
      display: "sideNavMenu.setting",
      link: "/admin/setting",
      linkPage: false,
      onclick: null,
      urlEndWith: "setting",
      className: "",
      permissionLevel: "Setting", //Advertisement
      regularIcon: <Megaphone24Regular />,
      filledIcon: <Megaphone24Filled style={{ color: "#C98383" }} />,
      eventKey: "setting",
      subMenu: [],
    },
  ];
}
export default SideBarMenu;
