import {
  Board24Filled,
  Board24Regular,
  Megaphone24Filled,
  Megaphone24Regular,
  PeopleCall24Filled,
  PeopleCall24Regular,
  PeopleCheckmark24Filled,
  PeopleCheckmark24Regular,
  PeopleTeam24Filled,
  PeopleTeam24Regular,
  ClipboardTaskAdd24Filled,
  ClipboardTaskAdd24Regular,
  Calendar24Regular,
  Calendar24Filled,
  CollectionsAdd24Regular,
  CollectionsAdd24Filled,
  ClockBill24Filled,
  ClockBill24Regular,
  DocumentBulletList24Regular,
  DocumentBulletList24Filled,
  ClipboardClock24Filled,
  ClipboardClock24Regular,
} from "@fluentui/react-icons";

class SideBarMenu {
  static menuForSuperAdmin = [
    {
      display: "sideNavMenu.dashboard",
      link: "/admin/dashboard",
      linkPage: false,
      onclick: null,
      urlEndWith: "dashboard",
      className: "",
      permissionLevel: "Dashboard",
      regularIcon: <Board24Regular />,
      filledIcon: <Board24Filled style={{ color: "#C98383" }} />,
      eventKey: "dashboard",
      subMenu: [],
    },

    {
      display: "sideNavMenu.users",
      link: "/admin/users",
      linkPage: false,
      onclick: null,
      urlEndWith: "users",
      className: "",
      permissionLevel: "Users",
      regularIcon: <PeopleTeam24Regular />,
      filledIcon: <PeopleTeam24Filled style={{ color: "#C98383" }} />,
      eventKey: "users",
      subMenu: [],
    },
    {
      display: "sideNavMenu.projects",
      link: "/admin/projects",
      linkPage: false,
      onclick: null,
      urlEndWith: "projects",
      className: "",
      permissionLevel: "Projects",
      regularIcon: <DocumentBulletList24Regular />,
      filledIcon: <DocumentBulletList24Filled style={{ color: "#C98383" }} />,
      eventKey: "projects",
      subMenu: [],
    },
    {
      display: "sideNavMenu.progressTimeline",
      link: "/admin/progressTimeline",
      linkPage: false,
      onclick: null,
      urlEndWith: "progressTimeline",
      className: "",
      permissionLevel: "Progress Timeline",
      regularIcon: <ClipboardClock24Regular />,
      filledIcon: <ClipboardClock24Filled style={{ color: "#C98383" }} />,
      eventKey: "progressTimeline",
      subMenu: [],
    },
    {
      display: "sideNavMenu.tasks",
      link: "/admin/tasks",
      linkPage: false,
      onclick: null,
      urlEndWith: "tasks",
      className: "",
      permissionLevel: "Task",
      regularIcon: <ClipboardTaskAdd24Regular />,
      filledIcon: <ClipboardTaskAdd24Filled style={{ color: "#C98383" }} />,
      eventKey: "tasks",
      subMenu: [],
    },
    {
      display: "sideNavMenu.room",
      link: "/admin/rooms",
      linkPage: false,
      onclick: null,
      urlEndWith: "room",
      className: "",
      permissionLevel: "Room",
      regularIcon: <CollectionsAdd24Regular />,
      filledIcon: <CollectionsAdd24Filled style={{ color: "#C98383" }} />,
      eventKey: "room",
      subMenu: [],
    },
    {
      display: "sideNavMenu.scheduleTime",
      link: "/admin/scheduleTime",
      linkPage: false,
      onclick: null,
      urlEndWith: "scheduleTime",
      className: "",
      permissionLevel: "Schedule Time",
      regularIcon: <ClockBill24Regular />,
      filledIcon: <ClockBill24Filled style={{ color: "#C98383" }} />,
      eventKey: "scheduleTime",
      subMenu: [],
    },
    {
      display: "sideNavMenu.attendance",
      link: "/admin/attendance",
      linkPage: false,
      onclick: null,
      urlEndWith: "attendance",
      className: "",
      permissionLevel: "Attendance",
      regularIcon: <Calendar24Regular />,
      filledIcon: <Calendar24Filled style={{ color: "#C98383" }} />,
      eventKey: "attendance",
      subMenu: [],
    },

    // {
    //   display: "sideNavMenu.transactions",
    //   link: "/admin/transactions/history",
    //   linkPage: false,
    //   onclick: null,
    //   urlEndWith: "transactions",
    //   className: "",
    //   permissionLevel: "Transactions",
    //   regularIcon: <PersonMoney24Regular />,
    //   filledIcon: <PersonMoney24Filled />,
    //   eventKey: "transactions",
    //   isExpandIconVisible: true,
    //   stylesForExpandedMenu: (pathUrl, displayName) =>
    //     // pass the url which is common in all the sub menus like /admin/inventory which is common in  challenges categories and golden tips
    //     pathUrl.includes("/admin/transactions") &&
    //     displayName === "sideNavMenu.transactions",

    //   subMenu: [
    //     {
    //       display: "sideNavMenu.history",
    //       link: "/admin/transactions/history",
    //       linkPage: false,
    //       onclick: null,
    //       urlEndWith: "history",
    //       className: "",
    //       permissionLevel: "History",
    //       regularIcon: <History24Regular />,
    //       filledIcon: <History24Filled />,
    //       eventKey: "history",
    //     },
    //     {
    //       display: "sideNavMenu.requests",
    //       link: "/admin/transactions/requests",
    //       linkPage: false,
    //       onclick: null,
    //       urlEndWith: "requests",
    //       className: "",
    //       permissionLevel: "Requests",
    //       regularIcon: <Money24Regular />,
    //       filledIcon: <Money24Filled />,
    //       eventKey: "requests",
    //     },
    //   ],
    // },

    {
      display: "sideNavMenu.security",
      link: "/admin/security/role",
      linkPage: false,
      onclick: null,
      urlEndWith: "security",
      className: "",
      permissionLevel: "Security",
      regularIcon: <PeopleCall24Regular />,
      filledIcon: <PeopleCall24Filled />,
      eventKey: "security",
      isExpandIconVisible: true,
      stylesForExpandedMenu: (pathUrl, displayName) =>
        // pass the url which is common in all the sub menus like /admin/security which is common in  roles
        pathUrl.includes("/admin/security") &&
        displayName === "sideNavMenu.security",
      subMenu: [
        {
          display: "sideNavMenu.role_function",
          link: "/admin/security/role",
          linkPage: false,
          onclick: null,
          urlEndWith: "role",
          className: "",
          permissionLevel: "Role",
          regularIcon: <PeopleCheckmark24Regular />,
          filledIcon: <PeopleCheckmark24Filled />,
          eventKey: "role",
        },
      ],
    },
    {
      display: "sideNavMenu.setting",
      link: "/admin/setting",
      linkPage: false,
      onclick: null,
      urlEndWith: "setting",
      className: "",
      permissionLevel: "Setting", //Advertisement
      regularIcon: <Megaphone24Regular />,
      filledIcon: <Megaphone24Filled style={{ color: "#C98383" }} />,
      eventKey: "setting",
      subMenu: [],
    },
  ];
}
export default SideBarMenu;
